feat(ci): add release pipeline

diff --git a/.github/workflows/sonar-checkstyle-workflows.yml b/.github/workflows/sonar-checkstyle-workflows.yml
--- a/.github/workflows/sonar-checkstyle-workflows.yml
+++ b/.github/workflows/sonar-checkstyle-workflows.yml
@@ -1,4 +1,5 @@
-name: sonar-checkstyle-workflows
+---
+name: Verify
 
 on:
   push:
@@ -16,27 +17,24 @@ jobs:
         java-version: ['21']
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
-      - name: Set up JDK
-        uses: actions/setup-java@v4
+      - uses: actions/setup-java@v5
         with:
           java-version: ${{ matrix.java-version }}
-          distribution: 'temurin'
+          distribution: temurin
 
-      - run: "./.ci/ci.sh install"
+      - run: ./.ci/ci.sh install
 
-# depreacted for now since SQ removed the application ZIP files needed for the integration tests
+# deprecated for now since SQ removed the application ZIP files needed for the integration tests
 #   integration-tests:
 #     runs-on: ubuntu-latest
 #     steps:
-#       - uses: actions/checkout@v2
-#       - name: Set up JDK 11
-#         uses: actions/setup-java@v1
+#       - uses: actions/checkout@v6
+#       - uses: actions/setup-java@v5
 #         with:
 #           java-version: 11
-#       - name: run integration tests
-#         run: "./.ci/ci.sh integration-tests"
+#       - run: ./.ci/ci.sh integration-tests
 
   nondex:
     name: Maven Nondex
@@ -47,41 +45,37 @@ jobs:
         java-version: ['21']
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
-      - name: Set up JDK
-        uses: actions/setup-java@v4
+      - uses: actions/setup-java@v5
         with:
           java-version: ${{ matrix.java-version }}
-          distribution: 'temurin'
+          distribution: temurin
 
-      - run: "./.ci/ci.sh nondex"
+      - run: ./.ci/ci.sh nondex
 
   execute-sonarqube-plugin:
     name: Execute SonarQube Plugin
     runs-on: ubuntu-latest
     strategy:
+      max-parallel: 4
       matrix:
-        sq-version: [ 'latest', '26.1.0.118079-community' ]
+        java-version: ['21']
+        sq-version: ['latest', '26.1.0.118079-community']
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v6
 
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
+      - uses: actions/setup-java@v5
         with:
-          java-version: '21'
-          distribution: 'temurin'
+          java-version: ${{ matrix.java-version }}
+          distribution: temurin
 
-      - name: Build Jar
-        run: mvn -e --no-transfer-progress package -Pno-validations
+      - run: ./.ci/ci.sh package
 
       - name: Run SonarQube
         run: |
           docker run -d --name sonarqube -p 9000:9000 -v ${{ github.workspace }}/target/:/opt/sonarqube/extensions/plugins/ sonarqube:${{ matrix.sq-version }}
-      - name: Check SonarQube is Up
-        run: |
           timeout 300 bash -c 'until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do echo "Waiting..."; sleep 5; done'
 
       - name: Generate SonarQube token
@@ -93,12 +87,13 @@ jobs:
           fi
           echo "SONAR_TOKEN=$SONAR_TOKEN" >> "$GITHUB_ENV"
 
-      - name: Execute SonarQube analysis
-        run: |
+      - run: |
           mvn -e --no-transfer-progress sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.token=$SONAR_TOKEN
-
-      - name: Check logs for error
-        run: docker logs sonarqube | grep "ERROR" || test $? = 1
+      - run: |
+          if docker logs sonarqube | grep -q "ERROR"; then
+            echo "SonarQube logs contain ERROR"
+            exit 1
+          fi
     
-      - name: Cleanup
-        run: docker stop sonarqube
+      - if: always()
+        run: docker stop sonarqube || true
